repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx
        args:
          - prettier
          - --write
          - "frontend/**/*.{js,jsx,json,md}"
        language: node
        types: [javascript, json, markdown]
        pass_filenames: true
        require_serial: true

      # - id: eslint
      #   name: eslint
      #   entry: npx
      #   args:
      #     - eslint
      #     - --fix
      #     - "backend/**/*.js"  # Ajuste o padrão para corresponder aos arquivos do backend
      #   language: node
      #   types: [javascript]
      #   pass_filenames: true
      #   require_serial: true

